///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddDelete_Trace recording.
    /// </summary>
    [TestModule("b6baf93e-a12d-458d-b0c1-274e5f5ac05e", ModuleType.Recording, 1)]
    public partial class AddDelete_Trace : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTestRepository repository.
        /// </summary>
        public static MyTestRepository repo = MyTestRepository.Instance;

        static AddDelete_Trace instance = new AddDelete_Trace();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddDelete_Trace()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddDelete_Trace Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.PictureIconToolBarButton1' at 19;24.", repo.VnaNG.PictureIconToolBarButton1Info, new RecordItemIndex(0));
            repo.VnaNG.PictureIconToolBarButton1.Click("19;24");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.TextTextTabItemToolBar1' at 83;31.", repo.VnaNG.TabSelectorToolBar.TextTextTabItemToolBar1Info, new RecordItemIndex(1));
            repo.VnaNG.TabSelectorToolBar.TextTextTabItemToolBar1.Click("83;31");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.TextTextCenter2' at 35;8.", repo.VnaNG.TabSelectorToolBar.TextTextCenter2Info, new RecordItemIndex(2));
            repo.VnaNG.TabSelectorToolBar.TextTextCenter2.Click("35;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 400ms.", new RecordItemIndex(3));
            Delay.Duration(400, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot4' with region {X=0,Y=0,Width=682,Height=582}) on item 'VnaNG.BackgroundItem1'.", repo.VnaNG.BackgroundItem1Info, new RecordItemIndex(4));
            Validate.CompareImage(repo.VnaNG.BackgroundItem1Info, BackgroundItem1_Screenshot4, BackgroundItem1_Screenshot4_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.TextTextCenter3' at 33;12.", repo.VnaNG.TabSelectorToolBar.TextTextCenter3Info, new RecordItemIndex(5));
            repo.VnaNG.TabSelectorToolBar.TextTextCenter3.Click("33;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 400ms.", new RecordItemIndex(6));
            Delay.Duration(400, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot5' with region {X=0,Y=0,Width=682,Height=582}) on item 'VnaNG.BackgroundItem1'.", repo.VnaNG.BackgroundItem1Info, new RecordItemIndex(7));
            Validate.CompareImage(repo.VnaNG.BackgroundItem1Info, BackgroundItem1_Screenshot5, BackgroundItem1_Screenshot5_Options);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage BackgroundItem1_Screenshot4
        { get { return repo.VnaNG.BackgroundItem1Info.GetScreenshot4(new Rectangle(0, 0, 682, 582)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions BackgroundItem1_Screenshot4_Options
        { get { return Imaging.FindOptions.Parse("0.999;None;0,0,682,582;True;10000000;0ms;3,522,59,58"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage BackgroundItem1_Screenshot5
        { get { return repo.VnaNG.BackgroundItem1Info.GetScreenshot5(new Rectangle(0, 0, 682, 582)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions BackgroundItem1_Screenshot5_Options
        { get { return Imaging.FindOptions.Parse("0.999;None;0,0,682,582;True;10000000;0ms;3,513,61,66"); } }

#endregion
    }
#pragma warning restore 0436
}
