///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Calibration_Kits_show_hide recording.
    /// </summary>
    [TestModule("5884560a-e9cb-4e74-8005-0891bf34578e", ModuleType.Recording, 1)]
    public partial class Calibration_Kits_show_hide : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTestRepository repository.
        /// </summary>
        public static MyTestRepository repo = MyTestRepository.Instance;

        static Calibration_Kits_show_hide instance = new Calibration_Kits_show_hide();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Calibration_Kits_show_hide()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Calibration_Kits_show_hide Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.ContainerRightSideToolBar.ContainerRoot' at 46;72.", repo.VnaNG.ContainerRightSideToolBar.ContainerRootInfo, new RecordItemIndex(0));
            repo.VnaNG.ContainerRightSideToolBar.ContainerRoot.Click("46;72");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.ContainerRightSideToolBar.ContainerHeaderTabItemLayout' at 230;29.", repo.VnaNG.ContainerRightSideToolBar.ContainerHeaderTabItemLayoutInfo, new RecordItemIndex(1));
            repo.VnaNG.ContainerRightSideToolBar.ContainerHeaderTabItemLayout.Click("230;29");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.ContainerRightSideToolBar.ContainerActionButton2' at 213;21.", repo.VnaNG.ContainerRightSideToolBar.ContainerActionButton2Info, new RecordItemIndex(2));
            repo.VnaNG.ContainerRightSideToolBar.ContainerActionButton2.Click("213;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.ContainerRightSideToolBar.ContainerActionButton2' at 208;19.", repo.VnaNG.ContainerRightSideToolBar.ContainerActionButton2Info, new RecordItemIndex(3));
            repo.VnaNG.ContainerRightSideToolBar.ContainerActionButton2.Click("208;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.ContainerRightSideToolBar.ContainerActionButton3' at 214;26.", repo.VnaNG.ContainerRightSideToolBar.ContainerActionButton3Info, new RecordItemIndex(4));
            repo.VnaNG.ContainerRightSideToolBar.ContainerActionButton3.Click("214;26");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.ContainerRightSideToolBar.ContainerActionButton3' at 212;28.", repo.VnaNG.ContainerRightSideToolBar.ContainerActionButton3Info, new RecordItemIndex(5));
            repo.VnaNG.ContainerRightSideToolBar.ContainerActionButton3.Click("212;28");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
