///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Cannel_max_min recording.
    /// </summary>
    [TestModule("36e7e984-fc64-4fef-97ff-b4e15ad2f0e6", ModuleType.Recording, 1)]
    public partial class Cannel_max_min : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTestRepository repository.
        /// </summary>
        public static MyTestRepository repo = MyTestRepository.Instance;

        static Cannel_max_min instance = new Cannel_max_min();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Cannel_max_min()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Cannel_max_min Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.ContainerRightSideToolBar.ContainerRoot4' at 55;71.", repo.VnaNG.ContainerRightSideToolBar.ContainerRoot4Info, new RecordItemIndex(0));
            repo.VnaNG.ContainerRightSideToolBar.ContainerRoot4.Click("55;71");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar1.ContainerHeaderTabItemLayout' at 193;30.", repo.VnaNG.TabSelectorToolBar1.ContainerHeaderTabItemLayoutInfo, new RecordItemIndex(1));
            repo.VnaNG.TabSelectorToolBar1.ContainerHeaderTabItemLayout.Click("193;30");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidator' at 133;21.", repo.VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidatorInfo, new RecordItemIndex(2));
            repo.VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidator.Click("133;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad9 7}' with focus on 'VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidator'.", repo.VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidatorInfo, new RecordItemIndex(3));
            repo.VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidator.PressKeys("{NumPad9 7}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidator'.", repo.VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidatorInfo, new RecordItemIndex(4));
            repo.VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidator.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot29' with region {X=0,Y=0,Width=679,Height=497}) on item 'VnaNG.BackgroundItem'.", repo.VnaNG.BackgroundItemInfo, new RecordItemIndex(5));
            Validate.CompareImage(repo.VnaNG.BackgroundItemInfo, BackgroundItem_Screenshot29, BackgroundItem_Screenshot29_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidator' at 86;13.", repo.VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidatorInfo, new RecordItemIndex(6));
            repo.VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidator.Click("86;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidator'.", repo.VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidatorInfo, new RecordItemIndex(7));
            repo.VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidator.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidator'.", repo.VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidatorInfo, new RecordItemIndex(8));
            repo.VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidator.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot30' with region {X=0,Y=0,Width=679,Height=497}) on item 'VnaNG.BackgroundItem'.", repo.VnaNG.BackgroundItemInfo, new RecordItemIndex(9));
            Validate.CompareImage(repo.VnaNG.BackgroundItemInfo, BackgroundItem_Screenshot30, BackgroundItem_Screenshot30_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar1.ContainerHeaderTabItemLayout1' at 231;19.", repo.VnaNG.TabSelectorToolBar1.ContainerHeaderTabItemLayout1Info, new RecordItemIndex(10));
            repo.VnaNG.TabSelectorToolBar1.ContainerHeaderTabItemLayout1.Click("231;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar1.ContainerHeaderTabItemLayout2' at 205;20.", repo.VnaNG.TabSelectorToolBar1.ContainerHeaderTabItemLayout2Info, new RecordItemIndex(11));
            repo.VnaNG.TabSelectorToolBar1.ContainerHeaderTabItemLayout2.Click("205;20");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidator1' at 139;14.", repo.VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidator1Info, new RecordItemIndex(12));
            repo.VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidator1.Click("139;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}{Return}' with focus on 'VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidator1'.", repo.VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidator1Info, new RecordItemIndex(13));
            repo.VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidator1.PressKeys("{NumPad1}{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot31' with region {X=0,Y=0,Width=679,Height=497}) on item 'VnaNG.BackgroundItem'.", repo.VnaNG.BackgroundItemInfo, new RecordItemIndex(14));
            Validate.CompareImage(repo.VnaNG.BackgroundItemInfo, BackgroundItem_Screenshot31, BackgroundItem_Screenshot31_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidator1' at 68;20.", repo.VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidator1Info, new RecordItemIndex(15));
            repo.VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidator1.Click("68;20");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer.List1' at 837;297.", repo.Explorer.List1Info, new RecordItemIndex(16));
            repo.Explorer.List1.Click("837;297");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad9 18}' with focus on 'VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidator1'.", repo.VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidator1Info, new RecordItemIndex(17));
            repo.VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidator1.PressKeys("{NumPad9 18}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidator1'.", repo.VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidator1Info, new RecordItemIndex(18));
            repo.VnaNG.TabSelectorToolBar1.BaseTextInputNumberValidator1.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot32' with region {X=0,Y=0,Width=679,Height=497}) on item 'VnaNG.BackgroundItem'.", repo.VnaNG.BackgroundItemInfo, new RecordItemIndex(19));
            Validate.CompareImage(repo.VnaNG.BackgroundItemInfo, BackgroundItem_Screenshot32, BackgroundItem_Screenshot32_Options);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage BackgroundItem_Screenshot29
        { get { return repo.VnaNG.BackgroundItemInfo.GetScreenshot29(new Rectangle(0, 0, 679, 497)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions BackgroundItem_Screenshot29_Options
        { get { return Imaging.FindOptions.Parse("0.95;None;0,0,679,497;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage BackgroundItem_Screenshot30
        { get { return repo.VnaNG.BackgroundItemInfo.GetScreenshot30(new Rectangle(0, 0, 679, 497)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions BackgroundItem_Screenshot30_Options
        { get { return Imaging.FindOptions.Parse("0.95;None;0,0,679,497;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage BackgroundItem_Screenshot31
        { get { return repo.VnaNG.BackgroundItemInfo.GetScreenshot31(new Rectangle(0, 0, 679, 497)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions BackgroundItem_Screenshot31_Options
        { get { return Imaging.FindOptions.Parse("0.95;None;0,0,679,497;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage BackgroundItem_Screenshot32
        { get { return repo.VnaNG.BackgroundItemInfo.GetScreenshot32(new Rectangle(0, 0, 679, 497)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions BackgroundItem_Screenshot32_Options
        { get { return Imaging.FindOptions.Parse("0.95;None;0,0,679,497;True;10000000;0ms"); } }

#endregion
    }
#pragma warning restore 0436
}
