///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Cannel_Scale_max_min recording.
    /// </summary>
    [TestModule("33910608-f7be-48c9-a926-1d7321db388d", ModuleType.Recording, 1)]
    public partial class Cannel_Scale_max_min : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTestRepository repository.
        /// </summary>
        public static MyTestRepository repo = MyTestRepository.Instance;

        static Cannel_Scale_max_min instance = new Cannel_Scale_max_min();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Cannel_Scale_max_min()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Cannel_Scale_max_min Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.ContainerRightSideToolBar.ContainerRoot4' at 51;63.", repo.VnaNG.ContainerRightSideToolBar.ContainerRoot4Info, new RecordItemIndex(0));
            repo.VnaNG.ContainerRightSideToolBar.ContainerRoot4.Click("51;63");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar1.ContainerHeaderTabItemLayout2' at 208;26.", repo.VnaNG.TabSelectorToolBar1.ContainerHeaderTabItemLayout2Info, new RecordItemIndex(1));
            repo.VnaNG.TabSelectorToolBar1.ContainerHeaderTabItemLayout2.Click("208;26");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar1.TextInputCommonUnitValidator' at 78;14.", repo.VnaNG.TabSelectorToolBar1.TextInputCommonUnitValidatorInfo, new RecordItemIndex(2));
            repo.VnaNG.TabSelectorToolBar1.TextInputCommonUnitValidator.Click("78;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad9 12}{NumPad9}{NumPad9}' with focus on 'VnaNG.TabSelectorToolBar1.TextInputCommonUnitValidator'.", repo.VnaNG.TabSelectorToolBar1.TextInputCommonUnitValidatorInfo, new RecordItemIndex(3));
            repo.VnaNG.TabSelectorToolBar1.TextInputCommonUnitValidator.PressKeys("{NumPad9 12}{NumPad9}{NumPad9}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'VnaNG.TabSelectorToolBar1.TextInputCommonUnitValidator'.", repo.VnaNG.TabSelectorToolBar1.TextInputCommonUnitValidatorInfo, new RecordItemIndex(4));
            repo.VnaNG.TabSelectorToolBar1.TextInputCommonUnitValidator.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot2' with region {X=0,Y=0,Width=679,Height=497}) on item 'VnaNG.BackgroundItem2'.", repo.VnaNG.BackgroundItem2Info, new RecordItemIndex(5));
            Validate.CompareImage(repo.VnaNG.BackgroundItem2Info, BackgroundItem2_Screenshot2, BackgroundItem2_Screenshot2_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar1.TextInputCommonUnitValidator' at 120;15.", repo.VnaNG.TabSelectorToolBar1.TextInputCommonUnitValidatorInfo, new RecordItemIndex(6));
            repo.VnaNG.TabSelectorToolBar1.TextInputCommonUnitValidator.Click("120;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad0}{Return}' with focus on 'VnaNG.TabSelectorToolBar1.TextInputCommonUnitValidator'.", repo.VnaNG.TabSelectorToolBar1.TextInputCommonUnitValidatorInfo, new RecordItemIndex(7));
            repo.VnaNG.TabSelectorToolBar1.TextInputCommonUnitValidator.PressKeys("{NumPad0}{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot3' with region {X=0,Y=0,Width=679,Height=497}) on item 'VnaNG.BackgroundItem2'.", repo.VnaNG.BackgroundItem2Info, new RecordItemIndex(8));
            Validate.CompareImage(repo.VnaNG.BackgroundItem2Info, BackgroundItem2_Screenshot3, BackgroundItem2_Screenshot3_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=196,Height=34}) on item 'VnaNG.TabSelectorToolBar1.TextInputCommonUnitValidator'.", repo.VnaNG.TabSelectorToolBar1.TextInputCommonUnitValidatorInfo, new RecordItemIndex(9));
            Validate.CompareImage(repo.VnaNG.TabSelectorToolBar1.TextInputCommonUnitValidatorInfo, TextInputCommonUnitValidator_Screenshot1, TextInputCommonUnitValidator_Screenshot1_Options);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage BackgroundItem2_Screenshot2
        { get { return repo.VnaNG.BackgroundItem2Info.GetScreenshot2(new Rectangle(0, 0, 679, 497)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions BackgroundItem2_Screenshot2_Options
        { get { return Imaging.FindOptions.Parse("0.95;None;0,0,679,497;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage BackgroundItem2_Screenshot3
        { get { return repo.VnaNG.BackgroundItem2Info.GetScreenshot3(new Rectangle(0, 0, 679, 497)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions BackgroundItem2_Screenshot3_Options
        { get { return Imaging.FindOptions.Parse("0.95;None;0,0,679,497;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage TextInputCommonUnitValidator_Screenshot1
        { get { return repo.VnaNG.TabSelectorToolBar1.TextInputCommonUnitValidatorInfo.GetScreenshot1(new Rectangle(0, 0, 196, 34)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions TextInputCommonUnitValidator_Screenshot1_Options
        { get { return Imaging.FindOptions.Parse("0.95;None;0,0,196,34;True;10000000;0ms"); } }

#endregion
    }
#pragma warning restore 0436
}
