///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Stimul_scale recording.
    /// </summary>
    [TestModule("52e81316-d67f-4e5e-8326-e9ad520c5e10", ModuleType.Recording, 1)]
    public partial class Stimul_scale : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTestRepository repository.
        /// </summary>
        public static MyTestRepository repo = MyTestRepository.Instance;

        static Stimul_scale instance = new Stimul_scale();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Stimul_scale()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Stimul_scale Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.ContainerRightSideToolBar.ContainerRoot2' at 53;61.", repo.VnaNG.ContainerRightSideToolBar.ContainerRoot2Info, new RecordItemIndex(0));
            repo.VnaNG.ContainerRightSideToolBar.ContainerRoot2.Click("53;61");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ContainerHeaderTabItemLayout1' at 219;27.", repo.VnaNG.TabSelectorToolBar.ContainerHeaderTabItemLayout1Info, new RecordItemIndex(1));
            repo.VnaNG.TabSelectorToolBar.ContainerHeaderTabItemLayout1.Click("219;27");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ContainerIndicatorSwitchControl' at 6;7.", repo.VnaNG.TabSelectorToolBar.ContainerIndicatorSwitchControlInfo, new RecordItemIndex(2));
            repo.VnaNG.TabSelectorToolBar.ContainerIndicatorSwitchControl.Click("6;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ContainerIndicatorSwitchControl' at 32;11.", repo.VnaNG.TabSelectorToolBar.ContainerIndicatorSwitchControlInfo, new RecordItemIndex(3));
            repo.VnaNG.TabSelectorToolBar.ContainerIndicatorSwitchControl.Click("32;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem' at 6;4.", repo.VnaNG.TabSelectorToolBar.ShaderItemInfo, new RecordItemIndex(4));
            repo.VnaNG.TabSelectorToolBar.ShaderItem.Click("6;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem' at 6;4.", repo.VnaNG.TabSelectorToolBar.ShaderItemInfo, new RecordItemIndex(5));
            repo.VnaNG.TabSelectorToolBar.ShaderItem.Click("6;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem' at 6;4.", repo.VnaNG.TabSelectorToolBar.ShaderItemInfo, new RecordItemIndex(6));
            repo.VnaNG.TabSelectorToolBar.ShaderItem.Click("6;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem' at 6;4.", repo.VnaNG.TabSelectorToolBar.ShaderItemInfo, new RecordItemIndex(7));
            repo.VnaNG.TabSelectorToolBar.ShaderItem.Click("6;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem' at 6;4.", repo.VnaNG.TabSelectorToolBar.ShaderItemInfo, new RecordItemIndex(8));
            repo.VnaNG.TabSelectorToolBar.ShaderItem.Click("6;4");
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating CompareImage (Screenshot: 'Screenshot20' with region {X=0,Y=0,Width=679,Height=497}) on item 'VnaNG.BackgroundItem'.", repo.VnaNG.BackgroundItemInfo, new RecordItemIndex(9));
                Validate.CompareImage(repo.VnaNG.BackgroundItemInfo, BackgroundItem_Screenshot20, BackgroundItem_Screenshot20_Options, null, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(9)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem1' at 7;5.", repo.VnaNG.TabSelectorToolBar.ShaderItem1Info, new RecordItemIndex(10));
            repo.VnaNG.TabSelectorToolBar.ShaderItem1.Click("7;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem1' at 7;5.", repo.VnaNG.TabSelectorToolBar.ShaderItem1Info, new RecordItemIndex(11));
            repo.VnaNG.TabSelectorToolBar.ShaderItem1.Click("7;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem1' at 7;5.", repo.VnaNG.TabSelectorToolBar.ShaderItem1Info, new RecordItemIndex(12));
            repo.VnaNG.TabSelectorToolBar.ShaderItem1.Click("7;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem1' at 7;5.", repo.VnaNG.TabSelectorToolBar.ShaderItem1Info, new RecordItemIndex(13));
            repo.VnaNG.TabSelectorToolBar.ShaderItem1.Click("7;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem1' at 7;5.", repo.VnaNG.TabSelectorToolBar.ShaderItem1Info, new RecordItemIndex(14));
            repo.VnaNG.TabSelectorToolBar.ShaderItem1.Click("7;5");
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating ContainsImage (Screenshot: 'MyTest_2_531ef5fa_rxlog1' with region {X=0,Y=0,Width=679,Height=497}) on item 'VnaNG.BackgroundItem'.", repo.VnaNG.BackgroundItemInfo, new RecordItemIndex(15));
                Validate.ContainsImage(repo.VnaNG.BackgroundItemInfo, BackgroundItem_MyTest_2_531ef5fa_rxlog1, BackgroundItem_MyTest_2_531ef5fa_rxlog1_Options, null, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(15)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem1' at 5;2.", repo.VnaNG.TabSelectorToolBar.ShaderItem1Info, new RecordItemIndex(16));
            repo.VnaNG.TabSelectorToolBar.ShaderItem1.Click("5;2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem1' at 5;2.", repo.VnaNG.TabSelectorToolBar.ShaderItem1Info, new RecordItemIndex(17));
            repo.VnaNG.TabSelectorToolBar.ShaderItem1.Click("5;2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem1' at 5;2.", repo.VnaNG.TabSelectorToolBar.ShaderItem1Info, new RecordItemIndex(18));
            repo.VnaNG.TabSelectorToolBar.ShaderItem1.Click("5;2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem1' at 5;2.", repo.VnaNG.TabSelectorToolBar.ShaderItem1Info, new RecordItemIndex(19));
            repo.VnaNG.TabSelectorToolBar.ShaderItem1.Click("5;2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem1' at 5;2.", repo.VnaNG.TabSelectorToolBar.ShaderItem1Info, new RecordItemIndex(20));
            repo.VnaNG.TabSelectorToolBar.ShaderItem1.Click("5;2");
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating ContainsImage (Screenshot: 'Screenshot21' with region {X=0,Y=0,Width=679,Height=497}) on item 'VnaNG.BackgroundItem'.", repo.VnaNG.BackgroundItemInfo, new RecordItemIndex(21));
                Validate.ContainsImage(repo.VnaNG.BackgroundItemInfo, BackgroundItem_Screenshot21, BackgroundItem_Screenshot21_Options, null, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(21)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem' at 7;4.", repo.VnaNG.TabSelectorToolBar.ShaderItemInfo, new RecordItemIndex(22));
            repo.VnaNG.TabSelectorToolBar.ShaderItem.Click("7;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem' at 7;4.", repo.VnaNG.TabSelectorToolBar.ShaderItemInfo, new RecordItemIndex(23));
            repo.VnaNG.TabSelectorToolBar.ShaderItem.Click("7;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem' at 7;4.", repo.VnaNG.TabSelectorToolBar.ShaderItemInfo, new RecordItemIndex(24));
            repo.VnaNG.TabSelectorToolBar.ShaderItem.Click("7;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'VnaNG.TabSelectorToolBar.ShaderItem' at 7;4.", repo.VnaNG.TabSelectorToolBar.ShaderItemInfo, new RecordItemIndex(25));
            repo.VnaNG.TabSelectorToolBar.ShaderItem.DoubleClick("7;4");
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating ContainsImage (Screenshot: 'Screenshot23' with region {X=0,Y=0,Width=679,Height=497}) on item 'VnaNG.BackgroundItem'.", repo.VnaNG.BackgroundItemInfo, new RecordItemIndex(26));
                Validate.ContainsImage(repo.VnaNG.BackgroundItemInfo, BackgroundItem_Screenshot23, BackgroundItem_Screenshot23_Options, null, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(26)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem2' at 3;6.", repo.VnaNG.TabSelectorToolBar.ShaderItem2Info, new RecordItemIndex(27));
            repo.VnaNG.TabSelectorToolBar.ShaderItem2.Click("3;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem2' at 3;6.", repo.VnaNG.TabSelectorToolBar.ShaderItem2Info, new RecordItemIndex(28));
            repo.VnaNG.TabSelectorToolBar.ShaderItem2.Click("3;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem2' at 3;6.", repo.VnaNG.TabSelectorToolBar.ShaderItem2Info, new RecordItemIndex(29));
            repo.VnaNG.TabSelectorToolBar.ShaderItem2.Click("3;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem2' at 3;6.", repo.VnaNG.TabSelectorToolBar.ShaderItem2Info, new RecordItemIndex(30));
            repo.VnaNG.TabSelectorToolBar.ShaderItem2.Click("3;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem2' at 3;6.", repo.VnaNG.TabSelectorToolBar.ShaderItem2Info, new RecordItemIndex(31));
            repo.VnaNG.TabSelectorToolBar.ShaderItem2.Click("3;6");
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating ContainsImage (Screenshot: 'Screenshot24' with region {X=0,Y=0,Width=679,Height=497}) on item 'VnaNG.BackgroundItem'.", repo.VnaNG.BackgroundItemInfo, new RecordItemIndex(32));
                Validate.ContainsImage(repo.VnaNG.BackgroundItemInfo, BackgroundItem_Screenshot24, BackgroundItem_Screenshot24_Options, null, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(32)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem3' at 3;5.", repo.VnaNG.TabSelectorToolBar.ShaderItem3Info, new RecordItemIndex(33));
            repo.VnaNG.TabSelectorToolBar.ShaderItem3.Click("3;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem3' at 3;5.", repo.VnaNG.TabSelectorToolBar.ShaderItem3Info, new RecordItemIndex(34));
            repo.VnaNG.TabSelectorToolBar.ShaderItem3.Click("3;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem3' at 3;5.", repo.VnaNG.TabSelectorToolBar.ShaderItem3Info, new RecordItemIndex(35));
            repo.VnaNG.TabSelectorToolBar.ShaderItem3.Click("3;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem3' at 3;5.", repo.VnaNG.TabSelectorToolBar.ShaderItem3Info, new RecordItemIndex(36));
            repo.VnaNG.TabSelectorToolBar.ShaderItem3.Click("3;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem3' at 3;5.", repo.VnaNG.TabSelectorToolBar.ShaderItem3Info, new RecordItemIndex(37));
            repo.VnaNG.TabSelectorToolBar.ShaderItem3.Click("3;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem3' at 3;5.", repo.VnaNG.TabSelectorToolBar.ShaderItem3Info, new RecordItemIndex(38));
            repo.VnaNG.TabSelectorToolBar.ShaderItem3.Click("3;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem3' at 3;5.", repo.VnaNG.TabSelectorToolBar.ShaderItem3Info, new RecordItemIndex(39));
            repo.VnaNG.TabSelectorToolBar.ShaderItem3.Click("3;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem3' at 3;5.", repo.VnaNG.TabSelectorToolBar.ShaderItem3Info, new RecordItemIndex(40));
            repo.VnaNG.TabSelectorToolBar.ShaderItem3.Click("3;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem3' at 3;5.", repo.VnaNG.TabSelectorToolBar.ShaderItem3Info, new RecordItemIndex(41));
            repo.VnaNG.TabSelectorToolBar.ShaderItem3.Click("3;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem3' at 3;5.", repo.VnaNG.TabSelectorToolBar.ShaderItem3Info, new RecordItemIndex(42));
            repo.VnaNG.TabSelectorToolBar.ShaderItem3.Click("3;5");
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating ContainsImage (Screenshot: 'Screenshot25' with region {X=0,Y=0,Width=679,Height=497}) on item 'VnaNG.BackgroundItem'.", repo.VnaNG.BackgroundItemInfo, new RecordItemIndex(43));
                Validate.ContainsImage(repo.VnaNG.BackgroundItemInfo, BackgroundItem_Screenshot25, BackgroundItem_Screenshot25_Options, null, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(43)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem4' at 5;4.", repo.VnaNG.TabSelectorToolBar.ShaderItem4Info, new RecordItemIndex(44));
            repo.VnaNG.TabSelectorToolBar.ShaderItem4.Click("5;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem4' at 5;4.", repo.VnaNG.TabSelectorToolBar.ShaderItem4Info, new RecordItemIndex(45));
            repo.VnaNG.TabSelectorToolBar.ShaderItem4.Click("5;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem4' at 5;4.", repo.VnaNG.TabSelectorToolBar.ShaderItem4Info, new RecordItemIndex(46));
            repo.VnaNG.TabSelectorToolBar.ShaderItem4.Click("5;4");
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating ContainsImage (Screenshot: 'MyTest_2_f05e2cb_rxlog1' with region {X=0,Y=0,Width=679,Height=497}) on item 'VnaNG.BackgroundItem'.", repo.VnaNG.BackgroundItemInfo, new RecordItemIndex(47));
                Validate.ContainsImage(repo.VnaNG.BackgroundItemInfo, BackgroundItem_MyTest_2_f05e2cb_rxlog1, BackgroundItem_MyTest_2_f05e2cb_rxlog1_Options, null, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(47)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem5' at 6;4.", repo.VnaNG.TabSelectorToolBar.ShaderItem5Info, new RecordItemIndex(48));
            repo.VnaNG.TabSelectorToolBar.ShaderItem5.Click("6;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem5' at 6;4.", repo.VnaNG.TabSelectorToolBar.ShaderItem5Info, new RecordItemIndex(49));
            repo.VnaNG.TabSelectorToolBar.ShaderItem5.Click("6;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem5' at 6;4.", repo.VnaNG.TabSelectorToolBar.ShaderItem5Info, new RecordItemIndex(50));
            repo.VnaNG.TabSelectorToolBar.ShaderItem5.Click("6;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem5' at 6;4.", repo.VnaNG.TabSelectorToolBar.ShaderItem5Info, new RecordItemIndex(51));
            repo.VnaNG.TabSelectorToolBar.ShaderItem5.Click("6;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem5' at 6;3.", repo.VnaNG.TabSelectorToolBar.ShaderItem5Info, new RecordItemIndex(52));
            repo.VnaNG.TabSelectorToolBar.ShaderItem5.Click("6;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem5' at 6;3.", repo.VnaNG.TabSelectorToolBar.ShaderItem5Info, new RecordItemIndex(53));
            repo.VnaNG.TabSelectorToolBar.ShaderItem5.Click("6;3");
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating ContainsImage (Screenshot: 'MyTest_2_83a0e2d0_rxlog1' with region {X=0,Y=0,Width=679,Height=497}) on item 'VnaNG.BackgroundItem'.", repo.VnaNG.BackgroundItemInfo, new RecordItemIndex(54));
                Validate.ContainsImage(repo.VnaNG.BackgroundItemInfo, BackgroundItem_MyTest_2_83a0e2d0_rxlog1, BackgroundItem_MyTest_2_83a0e2d0_rxlog1_Options, null, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(54)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem4' at 8;6.", repo.VnaNG.TabSelectorToolBar.ShaderItem4Info, new RecordItemIndex(55));
            repo.VnaNG.TabSelectorToolBar.ShaderItem4.Click("8;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem4' at 8;6.", repo.VnaNG.TabSelectorToolBar.ShaderItem4Info, new RecordItemIndex(56));
            repo.VnaNG.TabSelectorToolBar.ShaderItem4.Click("8;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem4' at 8;6.", repo.VnaNG.TabSelectorToolBar.ShaderItem4Info, new RecordItemIndex(57));
            repo.VnaNG.TabSelectorToolBar.ShaderItem4.Click("8;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem2' at 3;5.", repo.VnaNG.TabSelectorToolBar.ShaderItem2Info, new RecordItemIndex(58));
            repo.VnaNG.TabSelectorToolBar.ShaderItem2.Click("3;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'VnaNG.TabSelectorToolBar.ShaderItem2' at 3;5.", repo.VnaNG.TabSelectorToolBar.ShaderItem2Info, new RecordItemIndex(59));
            repo.VnaNG.TabSelectorToolBar.ShaderItem2.DoubleClick("3;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem2' at 3;5.", repo.VnaNG.TabSelectorToolBar.ShaderItem2Info, new RecordItemIndex(60));
            repo.VnaNG.TabSelectorToolBar.ShaderItem2.Click("3;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VnaNG.TabSelectorToolBar.ShaderItem2' at 4;5.", repo.VnaNG.TabSelectorToolBar.ShaderItem2Info, new RecordItemIndex(61));
            repo.VnaNG.TabSelectorToolBar.ShaderItem2.Click("4;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot28' with region {X=0,Y=0,Width=679,Height=497}) on item 'VnaNG.BackgroundItem'.", repo.VnaNG.BackgroundItemInfo, new RecordItemIndex(62));
            Validate.ContainsImage(repo.VnaNG.BackgroundItemInfo, BackgroundItem_Screenshot28, BackgroundItem_Screenshot28_Options);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage BackgroundItem_Screenshot20
        { get { return repo.VnaNG.BackgroundItemInfo.GetScreenshot20(new Rectangle(0, 0, 679, 497)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions BackgroundItem_Screenshot20_Options
        { get { return Imaging.FindOptions.Parse("0.998;EdgesSobel;0,0,679,497;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage BackgroundItem_MyTest_2_531ef5fa_rxlog1
        { get { return repo.VnaNG.BackgroundItemInfo.GetMyTest_2_531ef5fa_rxlog1(new Rectangle(0, 0, 679, 497)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions BackgroundItem_MyTest_2_531ef5fa_rxlog1_Options
        { get { return Imaging.FindOptions.Parse("0.998;EdgesSobel;0,0,0,0;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage BackgroundItem_Screenshot21
        { get { return repo.VnaNG.BackgroundItemInfo.GetScreenshot21(new Rectangle(0, 0, 679, 497)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions BackgroundItem_Screenshot21_Options
        { get { return Imaging.FindOptions.Parse("0.998;EdgesSobel;0,0,0,0;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage BackgroundItem_Screenshot23
        { get { return repo.VnaNG.BackgroundItemInfo.GetScreenshot23(new Rectangle(0, 0, 679, 497)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions BackgroundItem_Screenshot23_Options
        { get { return Imaging.FindOptions.Parse("0.998;EdgesSobel;0,0,0,0;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage BackgroundItem_Screenshot24
        { get { return repo.VnaNG.BackgroundItemInfo.GetScreenshot24(new Rectangle(0, 0, 679, 497)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions BackgroundItem_Screenshot24_Options
        { get { return Imaging.FindOptions.Parse("0.998;EdgesSobel;0,0,0,0;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage BackgroundItem_Screenshot25
        { get { return repo.VnaNG.BackgroundItemInfo.GetScreenshot25(new Rectangle(0, 0, 679, 497)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions BackgroundItem_Screenshot25_Options
        { get { return Imaging.FindOptions.Parse("0.998;EdgesSobel;0,0,0,0;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage BackgroundItem_MyTest_2_f05e2cb_rxlog1
        { get { return repo.VnaNG.BackgroundItemInfo.GetMyTest_2_f05e2cb_rxlog1(new Rectangle(0, 0, 679, 497)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions BackgroundItem_MyTest_2_f05e2cb_rxlog1_Options
        { get { return Imaging.FindOptions.Parse("0.998;EdgesSobel;0,0,0,0;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage BackgroundItem_MyTest_2_83a0e2d0_rxlog1
        { get { return repo.VnaNG.BackgroundItemInfo.GetMyTest_2_83a0e2d0_rxlog1(new Rectangle(0, 0, 679, 497)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions BackgroundItem_MyTest_2_83a0e2d0_rxlog1_Options
        { get { return Imaging.FindOptions.Parse("0.998;EdgesSobel;0,0,0,0;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage BackgroundItem_Screenshot28
        { get { return repo.VnaNG.BackgroundItemInfo.GetScreenshot28(new Rectangle(0, 0, 679, 497)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions BackgroundItem_Screenshot28_Options
        { get { return Imaging.FindOptions.Parse("0.998;EdgesSobel;0,0,0,0;True;10000000;0ms"); } }

#endregion
    }
#pragma warning restore 0436
}
